#!/usr/bin/env python
import glob
import xml.dom.minidom as minidom

#####################################
# XML Tree tools for manifest file  #	
#####################################
def templateTree():
	main = "<manifest></manifest>"
	tree = minidom.parseString(main)
	print(tree.toxml())

if __name__ == "__main__":
	print glob.glob('*')
	templateTree()

